apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-brochure-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: travel-brochure-api
  template:
    metadata:
      labels:
        component: travel-brochure-api
    spec:
      containers:
        - name: travel-brochure-api
          image: asia.gcr.io/PROJECT_ID/travel-brochure-api:latest
          resources:
            limits:
              cpu: "120m"
              memory: "200Mi"
            requests:
              cpu: "50m"
              memory: "100Mi"
          ports:
            - containerPort: 4000
          env:
            - name: REDIS_URI
              value: redis://redis-cluster-ip-service:6379
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-password
                  key: MYSQL_PASSWORD
            - name: MYSQL_URI
              value: mysql://admin:$(MYSQL_PASSWORD)@travel-brochure-mysql-cluster-ip-service:3306/travel_brochure
            - name: BASE_URL
              valueFrom:
                secretKeyRef:
                  name: travel-brochure-api-secret
                  key: BASE_URL
            - name: GOOGLE_APPLICATION_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: travel-brochure-api-secret
                  key: GOOGLE_APPLICATION_CREDENTIALS
            - name: GOOGLE_CLOUD_STORAGE_BUCKET
              valueFrom:
                secretKeyRef:
                  name: travel-brochure-api-secret
                  key: GOOGLE_CLOUD_STORAGE_BUCKET
            - name: GOOGLE_APP_SCRIPT_CONFIRM_SIGN_UP_URL
              valueFrom:
                secretKeyRef:
                  name: travel-brochure-api-secret
                  key: GOOGLE_APP_SCRIPT_CONFIRM_SIGN_UP_URL
            - name: GOOGLE_APP_SCRIPT_CONFIRM_EMAIL_URL
              valueFrom:
                secretKeyRef:
                  name: travel-brochure-api-secret
                  key: GOOGLE_APP_SCRIPT_CONFIRM_EMAIL_URL
            - name: GOOGLE_APP_SCRIPT_RESET_PASSWORD_URL
              valueFrom:
                secretKeyRef:
                  name: travel-brochure-api-secret
                  key: GOOGLE_APP_SCRIPT_RESET_PASSWORD_URL
            - name: GOOGLE_APP_SCRIPT_CONTACT_URL
              valueFrom:
                secretKeyRef:
                  name: travel-brochure-api-secret
                  key: GOOGLE_APP_SCRIPT_CONTACT_URL